""""""""""""""""""""""""""""""""""
"         core settings          "
""""""""""""""""""""""""""""""""""

set background=light
"colorscheme solarized
colorscheme newspaper

"colorscheme wombat
""""""""""""""""""""""""""""""""""
"           settings             "
""""""""""""""""""""""""""""""""""
if expand("%") == ".git/COMMIT_EDITMSG"
  finish
endif

set guioptions-=rL
set guioptions-=m
" ビジュアル選択(D&D他)を自動的にクリップボードへ (:help guioptions_a)
set guioptions+=a
" クリップボード
set clipboard+=unnamed
" ツールバー非表示
set guioptions-=T

set guitablabel=%t

set linespace=4


if has('vim_starting')
  if has('win32')
    " font 
    if exists('g:my_gui_font')
      let &guifont=g:my_gui_font
    else
      "set guifont=MS_Gothic:h10:cSHIFTJIS
      set guifont=MeiryoKe_Gothic:h10:cSHIFTJIS 
    endif

    set columns=88
  elseif has('mac')
    " フォント
    set guifont=Osaka-Mono:h14
    " 透明度
    if g:colors_name == 'solarized'
    else
      set transparency=5
    endif
    " esc 時に ime off mac vim only
    set imda
    " ウインドウ幅
    if &columns == 80
      set columns=95
    endif
    " ウインドウの高さ
    set lines=37
    "
  elseif has('unix')
    " 行間
    " アンチエイリアス
    set antialias
    " フォント
    set guifont=MeiryoKe_Gothic\ 11.5
    " 幅
    set columns=100
    " 高さ
    set lines=28
  endif
endif


" コマンドラインの高さ
set cmdheight=1

"*******************************************************
"*                   保存・終了                        *
"*******************************************************
" gui の時だけ。Terminal ではやらない。
command! -nargs=? -bang WQ  call s:WriteClose('<bang>')
function! s:WriteClose(bang)
  if a:bang == ''
    write | bd
  else
    write! | bd!
  endif
endfunction
AlterCommand q Kwbd
AlterCommand wq WQ
""""""""""""""""""""""""""""""""""
"             other              "
""""""""""""""""""""""""""""""""""
nnoremap <Space>s. :<C-u>source $MYVIMRC<Enter>:<C-u>source $MYGVIMRC<Enter>

hi ModeMsg guifg=bg guibg=bg

if g:colors_name == 'solarized'
  hi Normal     guifg=#313131
  hi Pmenu      guifg=#FFFDD6  guibg=black
  hi PmenuSel   guifg=#F0FF93  guibg=#000000
  "hi Identifier guifg=blue
  hi vimMap     guifg=brown
  hi vimCommand guifg=brown
  hi helpHyperTextEntry guifg=#276549
  hi Comment    guifg=gray

  hi tweetvim_reply            guifg=brown
  hi tweetvim_screen_name      guifg=#2C773D
  hi tweetvim_at_screen_name   guifg=#2C773D
  hi tweetvim_rt_count         guifg=#FF0000
  hi tweetvim_appendix         guifg=gray
  hi tweetvim_star             guifg=orange
  hi tweetvim_separator        guifg=gray
  hi tweetvim_separator_title  guifg=gray
  hi tweetvim_hash_tag         guifg=purple

endif

if g:colors_name == 'newspaper'
  if has('mac')
    set transparency=0
  endif
  "hi Cursor  guifg=black    guibg=orange
  hi Cursor  guifg=bg   guibg=#557788
  "hi CursorLine guibg=#D2D2D2
  hi CursorLine guibg=#cccfbf
  hi CursorLineNr guifg=#666677 guibg=#cccfbf gui=none
  hi Comment guifg=darkgray gui=none
  hi helpExample guifg=darkblue
  hi vimshellPrompt guifg=darkgreen
  hi PmenuSel ctermfg=255 ctermbg=21 gui=none guifg=#ffffff guibg=#716d51 
  hi Error   guifg=red gui=none
  "hi StatusLine   guibg=#cccfbf guifg=#716d51 gui=none 
  "hi StatusLineNC guibg=#cccfbd guifg=#716d51 gui=none term=reverse ctermfg=253 ctermbg=110 

  hi tweetvim_reply            guifg=brown guibg=#d3d47a
  hi tweetvim_screen_name      guifg=#2C773D
  hi tweetvim_at_screen_name   guifg=#2C773D
  hi tweetvim_rt_count         guifg=#FF0000
  hi tweetvim_appendix         guifg=gray
  hi tweetvim_star             guifg=orange
  hi tweetvim_separator        guifg=gray
  hi tweetvim_separator_title  guifg=gray
  hi tweetvim_hash_tag         guifg=blue

  hi ModeMsg   guifg=darkgray gui=none
  hi Question  guifg=darkgray gui=none
  hi Search    guifg=#ffffff guibg=#7B7939
  hi IncSearch guifg=#000000 guibg=#adadad
  hi VimError  guibg=#dcdda8

  hi note_strong guifg=red

  let g:vimshell_escape_colors = ['#6c6c6c', '#ff6666', '#0000ff', '#a22727', '#1e95fd', '#ff13ff', 'darkgreen', '#C0C0C0', '#383838', '#ff4444', '#44ff44', '#ffb30a', '#6699ff', '#f820ff', '#4ae2e2', '#ffffff']

  hi J6uil_separator guifg=gray
  hi J6uil_quotation guifg=#557788

  hi uniteSource__FileMru_Time guifg=#9f9f9f
  hi uniteSource__Buffer_Time  guifg=#9f9f9f
  hi uniteSource__Buffer_Name  guifg=#000000
endi


if g:colors_name == 'wonbat'
  " カーソルオレンジ"
  hi Cursor   guifg=bg    guibg=orange
  hi Visual   guifg=black guibg=#bde682
  hi VimShellUserPrompt guifg=#95e454
  hi VimShellPrompt guifg=#8ac6f2 gui=NONE
  hi VimShellError  guifg=#e5786d
  hi Comment             gui=none
  hi String              gui=none
  hi StatusLine  gui=none
  hi IncSearch guifg=red guibg=white
  hi Search term=reverse ctermfg=0 ctermbg=14 guifg=Black guibg=#EAE49D

  hi txtHeader  guifg=#cae682 gui=bold
  hi txtHeader2 guifg=orange gui=underline
  hi txtBold    guifg=#cae682 gui=bold
  "highlight uniteCandidateInputKeyword guifg=#cae682 gui=bold
  "hi uniteCandidateInputKeyword guifg=orange
  hi Unite_Cursor_Line guibg=#2F434F
  "hi Unite_Cursor_Line guibg=#000000
  "hi Unite_Cursor_Line guibg=#2F4F4F
  hi Unite_Cursor_Line guibg=#00008b
  "let g:unite_cursor_line_highlight = 'Unite_Cursor_Line'
  " ポップアップの選択中
  "hi PmenuSel guibg=magenta guifg=white
  "hi Pmenu guibg=white guifg=black
  hi clear Conceal
  hi Conceal  ctermfg=7 ctermbg=8 guifg=orange

  hi Title gui=none guifg=orange
endif
